$('.extra__list').owlCarousel({
    loop:true,
    nav:true,
    margin:10,
    dots: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2,
        },
        768:{
            items:3,
        },
        992:{
            items:4,
        }
    }
});

$('.feedback__list').owlCarousel({
    loop:true,
    nav:true,
    margin:10,
    dots: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
        },
        768:{
            items:2,
        },
        992:{
            items:3,
        }
    }
});

$('.team__list--slider').owlCarousel({
    loop:true,
    nav:true,
    margin:20,
    dots: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2,
        },
        768:{
            items:3,
        },
        992:{
            items:4,
        }
    }
});